version: "3.9"

services:
  database:
    image: postgres
    container_name: react_trab
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local